'use client';

import { usePathname } from 'next/navigation';
import Footer from '../components/layout/Footer';
import Sidebar from '../components/layout/Sidebar';
import AdminNav from '../components/layout/adminNav';
import './globals.css';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { io } from "socket.io-client";
import { useNotificationData, useWebSocket } from '../Store/useAdminStore';
import { useEffect } from 'react';

const queryClient = new QueryClient();


// export const metadata = {
//   title: "Sealium",
//   description: "Generated by create next app",
// };
export default function RootLayout({ children }) {
  const pathname = usePathname();
  const {setSocket} = useWebSocket();
  const {setNotification} = useNotificationData();

  useEffect(() => {
    // connect to backend WebSocket
    const socket = io('https://api.sealiumback.store', {
      transports: ["websocket"], // force pure WebSocket, skip long polling
    });
    console.log('socketconnect', socket)
    setSocket(socket)
  
    // when connected
    socket.on("connect", () => {
      console.log("Connected with id:", socket.id);
    });
  
    // listen for notifications
    socket.on("receiveNotification", (data) => {
      console.log("🔔 Notification:", data);
      setNotification(data)
    });
  
    // listen for messages
    socket.on("receiveMessage", (data) => {
      console.log("💬 Message:", data);
    });
  
    // cleanup on component unmount
    return () => {
      socket.disconnect();
    };
  }, []);
  

  const hideLayout =
    pathname === '/' || pathname === '/admin/signup' || pathname === '/reset-password';

  return (
    <html lang="ko">
      <head>
        {/* 스크롤바 스타일을 위한 CSS 추가 */}
        <style jsx global>{`
          /* 전체 스크롤바 스타일 */
          ::-webkit-scrollbar {
            width: 15px; /* 스크롤바 너비 */
          }
          
          /* 스크롤바 트랙(배경) 스타일 */
          ::-webkit-scrollbar-track {
            // background-color: #FAFCFF; /* bg-amber-500과 비슷한 색상 */
            border-radius: 15px 15px 15px 15px; /* 둥근 모서리 */
          }
          
          /* 스크롤바 썸(드래그하는 부분) 스타일 */
          ::-webkit-scrollbar-thumb {
            background-color:  #7797AC; /* bg-amber-600과 비슷한 색상 */
            border-radius: 8px; /* 둥근 모서리 */
            border: 2px solid #D9D8D5; /* 트랙과 구분되는 테두리 */
          }
          
          /* 마우스 오버 시 스크롤바 썸 스타일 */
          ::-webkit-scrollbar-thumb:hover {
            background-color: #2A4259; /* bg-amber-700과 비슷한 색상 */
          }
        `}</style>
      </head>
      <body  >
        <QueryClientProvider client={queryClient}>
          {hideLayout ? (
            <>{children}</>
          ) : (
            <div className='w-screen h-[100vh] bg-deepnavy' >
              <div className='    h-[100vh] border-12 overflow-y-scroll overflow-hidden  border-deepnavy  '>
                {/* <div className=' overflow-y-scroll h-[calc(100vh-24px)]' > */}
                  <div className="flex min-h-screen">
                    <Sidebar />
                    <div className="flex flex-col flex-1">
                      {/* 전역 상단 AdminNav */}
                      <AdminNav />
                      <main className="flex-1">{children}</main>
                      {/* <Footer /> */}
                    </div>
                  </div>
                </div>
              {/* </div> */}
            </div>)}
        </QueryClientProvider>
      </body>
    </html>
  );
}
